import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-neutral-950 text-neutral-100 antialiased">
        <div className="relative min-h-screen flex flex-col overflow-hidden">
          
          {/* Top radial glow */}
          <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_top,rgba(234,179,8,0.15),transparent_60%)]" />
          
          {/* Bottom gold haze */}
          <div className="pointer-events-none absolute inset-0 bg-[linear-gradient(to_top,rgba(234,179,8,0.08),transparent_40%)]" />

          <div className="flex-1">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
